update README to clarify hash functionality not needed
TheOdinProject/custom_enumerable_project pull request #6
Opened 2022-09-14 15:47 UTC by Forthoney

Added a sentence clarifying the scope of the task to just Arrays in line 67 of README.md

2022-11-19 23:00 UTC, ChargrilledChook requested changes
Apologies for the delay getting back to you on this one @Forthoney. Great change, I only have one small suggestion. Let me know your thoughts then we can get this one merged :rocket:

2022-11-19 23:00 UTC, ChargrilledChook commented on README.md
> +The following table has the methods you will need to implement along with their associated specs, as outlined in the project instructions. The methods in the Enumerable module do not need to work wit
```suggestion
The following table has the methods you will need to implement along with their associated specs, as outlined in the project instructions. The methods in the Enumerable module only need to work with Arrays, but you can challenge yourself and try to make them work for Hashes as well.
```
Great idea, but I think it flows a little better without the slight double negative. What do you think?

2022-11-20 05:45 UTC, Forthoney commented
@ChargrilledChook Sounds much clearer! Thanks for the feedback

2022-11-20 07:31 UTC, ChargrilledChook approved these changes
Looks great, thanks @Forthoney!

2022-11-20 07:31 UTC, merged